-- MySQL Script generated by MySQL Workbench
-- 2020년 10월 31일 (토) 오후 10시 02분 22초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema radius
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `radius` ;

-- -----------------------------------------------------
-- Schema radius
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radius` DEFAULT CHARACTER SET utf8 ;
USE `radius` ;

-- -----------------------------------------------------
-- Table `radius`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`users` ;

CREATE TABLE IF NOT EXISTS `radius`.`users` (
  `user_id` VARCHAR(128) NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `passwd` VARCHAR(90) NOT NULL,
  `status` TINYINT NOT NULL,
  `oldpasswd` VARCHAR(90) NULL,
  `passwd_lifetime` DATETIME NULL,
  `passwd_failcount` SMALLINT NULL,
  `last_passwd_changed` DATETIME NULL,
  `valid_start_date` DATETIME NULL,
  `valid_end_date` DATETIME NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `last_login` DATETIME NULL,
  `mac_check` TINYINT NULL,
  `level` TINYINT NULL,
  `simultaneous` SMALLINT NULL,
  `vlanid` SMALLINT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `changed` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`user_id`),
  INDEX `user_name_idx` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`groups` ;

CREATE TABLE IF NOT EXISTS `radius`.`groups` (
  `group_id` VARCHAR(128) NOT NULL,
  `group_name` VARCHAR(64) NOT NULL,
  `parent_group_id` VARCHAR(128) NOT NULL,
  `mac_check` TINYINT NULL,
  `vlanid` SMALLINT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `changed` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`group_id`),
  INDEX `group_name_idx` (`group_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`mac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`mac` ;

CREATE TABLE IF NOT EXISTS `radius`.`mac` (
  `mac` CHAR(12) NOT NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`mac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`users_mac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`users_mac` ;

CREATE TABLE IF NOT EXISTS `radius`.`users_mac` (
  `user_id` VARCHAR(128) NOT NULL,
  `mac_mac` CHAR(12) NOT NULL,
  INDEX `fk_users_mac_users_idx` (`user_id` ASC),
  INDEX `fk_users_mac_mac_idx` (`mac_mac` ASC),
  CONSTRAINT `fk_users_mac_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `radius`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_mac_mac`
    FOREIGN KEY (`mac_mac`)
    REFERENCES `radius`.`mac` (`mac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`nas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`nas` ;

CREATE TABLE IF NOT EXISTS `radius`.`nas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nasname` VARCHAR(128) NOT NULL,
  `shortname` VARCHAR(32) NULL,
  `type` VARCHAR(30) NULL DEFAULT 'other',
  `ports` INT NULL,
  `secret` VARCHAR(60) NULL,
  `server` VARCHAR(64) NULL,
  `community` VARCHAR(50) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`radpostauth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`radpostauth` ;

CREATE TABLE IF NOT EXISTS `radius`.`radpostauth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NULL,
  `reply` VARCHAR(32) NULL,
  `result` TINYINT NULL,
  `reason` VARCHAR(200) NULL,
  `authdate` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`radacct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`radacct` ;

CREATE TABLE IF NOT EXISTS `radius`.`radacct` (
  `radacctid` INT NOT NULL AUTO_INCREMENT,
  `acctsessionid` VARCHAR(64) NOT NULL DEFAULT '',
  `acctuniqueid` VARCHAR(32) NULL DEFAULT '',
  `username` VARCHAR(64) NULL DEFAULT '',
  `realm` VARCHAR(64) NULL DEFAULT '',
  `nasipaddress` VARCHAR(15) NULL DEFAULT '',
  `nasportid` VARCHAR(32) NULL,
  `nasporttype` VARCHAR(32) NULL,
  `acctstarttime` DATETIME NULL,
  `acctupdatetime` DATETIME NULL,
  `acctstoptime` DATETIME NULL,
  `acctinterval` INT NULL,
  `acctsessiontime` INT NULL,
  `acctauthentic` VARCHAR(32) NULL,
  `connectinfo_start` VARCHAR(50) NULL,
  `connectinfo_stop` VARCHAR(50) NULL,
  `acctinputoctets` BIGINT NULL,
  `acctoutputoctets` BIGINT NULL,
  `calledstationid` VARCHAR(50) NULL DEFAULT '',
  `callingstationid` VARCHAR(50) NULL DEFAULT '',
  `acctterminatecause` VARCHAR(32) NULL DEFAULT '',
  `servicetype` VARCHAR(32) NULL,
  `framedprotocol` VARCHAR(32) NULL,
  `framedipaddress` VARCHAR(15) NULL DEFAULT '',
  `framedipv6address` VARCHAR(45) NULL DEFAULT '',
  `framedipv6prefix` VARCHAR(45) NULL DEFAULT '',
  `framedinterfaceid` VARCHAR(44) NULL DEFAULT '',
  `delegatedipv6prefix` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`radacctid`),
  UNIQUE INDEX `acctsessiontime_UNIQUE` (`acctsessiontime` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`users_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`users_groups` ;

CREATE TABLE IF NOT EXISTS `radius`.`users_groups` (
  `user_id` VARCHAR(128) NOT NULL,
  `group_id` VARCHAR(128) NOT NULL,
  INDEX `fk_users_groups_users_idx` (`user_id` ASC),
  INDEX `fk_users_groups_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `radius`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `radius`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`rad_users_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`rad_users_reply` ;

CREATE TABLE IF NOT EXISTS `radius`.`rad_users_reply` (
  `user_id` VARCHAR(128) NOT NULL,
  `attribute` VARCHAR(128) NULL,
  `value` VARCHAR(256) NULL,
  INDEX `fk_rad_users_reply_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_rad_users_reply_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `radius`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radius`.`rad_groups_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `radius`.`rad_groups_reply` ;

CREATE TABLE IF NOT EXISTS `radius`.`rad_groups_reply` (
  `group_id` VARCHAR(128) NOT NULL,
  `attribute` VARCHAR(128) NULL,
  `value` VARCHAR(256) NULL,
  INDEX `fk_rad_groups_reply_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_rad_groups_reply_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `radius`.`groups` (`group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
